@startuml
'https://plantuml.com/class-diagram

abstract class BaseHaddockModule {
log
previous_path
_run
run
reset_params
save_config
update_params
}

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml