#!/bin/bash/ 
sh create-local-job.sh dpp 2 gl2 1
sh create-local-job.sh dpp 2 gl2 2
sh create-local-job.sh dpp 2 gl2 3
sh create-local-job.sh dpp 2 gl2 4
sh create-local-job.sh dpp 2 gl2 5
sh create-local-job.sh dpp 2 gl2 6
sh create-local-job.sh dpp 2 gl2 7
sh create-local-job.sh dpp 2 gl2 8
sh create-local-job.sh dpp 2 gl2 9
sh create-local-job.sh dpp 2 gl2 10
sh create-local-job.sh dpp 4 gl2 1
sh create-local-job.sh dpp 4 gl2 2
sh create-local-job.sh dpp 4 gl2 3
sh create-local-job.sh dpp 4 gl2 4
sh create-local-job.sh dpp 4 gl2 5
sh create-local-job.sh dpp 4 gl2 6
sh create-local-job.sh dpp 4 gl2 7
sh create-local-job.sh dpp 4 gl2 8
sh create-local-job.sh dpp 4 gl2 9
sh create-local-job.sh dpp 4 gl2 10
sh create-local-job.sh dpp 8 gl2 1
sh create-local-job.sh dpp 8 gl2 2
sh create-local-job.sh dpp 8 gl2 3
sh create-local-job.sh dpp 8 gl2 4
sh create-local-job.sh dpp 8 gl2 5
sh create-local-job.sh dpp 8 gl2 6
sh create-local-job.sh dpp 8 gl2 7
sh create-local-job.sh dpp 8 gl2 8
sh create-local-job.sh dpp 8 gl2 9
sh create-local-job.sh dpp 8 gl2 10
sh create-local-job.sh dpp 2 gl6 1
sh create-local-job.sh dpp 2 gl6 2
sh create-local-job.sh dpp 2 gl6 3
sh create-local-job.sh dpp 2 gl6 4
sh create-local-job.sh dpp 2 gl6 5
sh create-local-job.sh dpp 2 gl6 6
sh create-local-job.sh dpp 2 gl6 7
sh create-local-job.sh dpp 2 gl6 8
sh create-local-job.sh dpp 2 gl6 9
sh create-local-job.sh dpp 2 gl6 10
sh create-local-job.sh dpp 4 gl6 1
sh create-local-job.sh dpp 4 gl6 2
sh create-local-job.sh dpp 4 gl6 3
sh create-local-job.sh dpp 4 gl6 4
sh create-local-job.sh dpp 4 gl6 5
sh create-local-job.sh dpp 4 gl6 6
sh create-local-job.sh dpp 4 gl6 7
sh create-local-job.sh dpp 4 gl6 8
sh create-local-job.sh dpp 4 gl6 9
sh create-local-job.sh dpp 4 gl6 10
sh create-local-job.sh dpp 8 gl6 1
sh create-local-job.sh dpp 8 gl6 2
sh create-local-job.sh dpp 8 gl6 3
sh create-local-job.sh dpp 8 gl6 4
sh create-local-job.sh dpp 8 gl6 5
sh create-local-job.sh dpp 8 gl6 6
sh create-local-job.sh dpp 8 gl6 7
sh create-local-job.sh dpp 8 gl6 8
sh create-local-job.sh dpp 8 gl6 9
sh create-local-job.sh dpp 8 gl6 10
sh create-local-job.sh daa 2 gl2 1
sh create-local-job.sh daa 2 gl2 2
sh create-local-job.sh daa 2 gl2 3
sh create-local-job.sh daa 2 gl2 4
sh create-local-job.sh daa 2 gl2 5
sh create-local-job.sh daa 2 gl2 6
sh create-local-job.sh daa 2 gl2 7
sh create-local-job.sh daa 2 gl2 8
sh create-local-job.sh daa 2 gl2 9
sh create-local-job.sh daa 2 gl2 10
sh create-local-job.sh daa 4 gl2 1
sh create-local-job.sh daa 4 gl2 2
sh create-local-job.sh daa 4 gl2 3
sh create-local-job.sh daa 4 gl2 4
sh create-local-job.sh daa 4 gl2 5
sh create-local-job.sh daa 4 gl2 6
sh create-local-job.sh daa 4 gl2 7
sh create-local-job.sh daa 4 gl2 8
sh create-local-job.sh daa 4 gl2 9
sh create-local-job.sh daa 4 gl2 10
sh create-local-job.sh daa 8 gl2 1
sh create-local-job.sh daa 8 gl2 2
sh create-local-job.sh daa 8 gl2 3
sh create-local-job.sh daa 8 gl2 4
sh create-local-job.sh daa 8 gl2 5
sh create-local-job.sh daa 8 gl2 6
sh create-local-job.sh daa 8 gl2 7
sh create-local-job.sh daa 8 gl2 8
sh create-local-job.sh daa 8 gl2 9
sh create-local-job.sh daa 8 gl2 10
sh create-local-job.sh daa 2 gl6 1
sh create-local-job.sh daa 2 gl6 2
sh create-local-job.sh daa 2 gl6 3
sh create-local-job.sh daa 2 gl6 4
sh create-local-job.sh daa 2 gl6 5
sh create-local-job.sh daa 2 gl6 6
sh create-local-job.sh daa 2 gl6 7
sh create-local-job.sh daa 2 gl6 8
sh create-local-job.sh daa 2 gl6 9
sh create-local-job.sh daa 2 gl6 10
sh create-local-job.sh daa 4 gl6 1
sh create-local-job.sh daa 4 gl6 2
sh create-local-job.sh daa 4 gl6 3
sh create-local-job.sh daa 4 gl6 4
sh create-local-job.sh daa 4 gl6 5
sh create-local-job.sh daa 4 gl6 6
sh create-local-job.sh daa 4 gl6 7
sh create-local-job.sh daa 4 gl6 8
sh create-local-job.sh daa 4 gl6 9
sh create-local-job.sh daa 4 gl6 10
sh create-local-job.sh daa 8 gl6 1
sh create-local-job.sh daa 8 gl6 2
sh create-local-job.sh daa 8 gl6 3
sh create-local-job.sh daa 8 gl6 4
sh create-local-job.sh daa 8 gl6 5
sh create-local-job.sh daa 8 gl6 6
sh create-local-job.sh daa 8 gl6 7
sh create-local-job.sh daa 8 gl6 8
sh create-local-job.sh daa 8 gl6 9
sh create-local-job.sh daa 8 gl6 10
sh create-local-job.sh dpp 16 gl6 1
sh create-local-job.sh dpp 16 gl6 2
sh create-local-job.sh dpp 16 gl6 3
sh create-local-job.sh dpp 16 gl6 4
sh create-local-job.sh dpp 16 gl6 5
sh create-local-job.sh dpp 16 gl6 6
sh create-local-job.sh dpp 16 gl6 7
sh create-local-job.sh dpp 16 gl6 8
sh create-local-job.sh dpp 16 gl6 9
sh create-local-job.sh dpp 16 gl6 10
sh create-local-job.sh dpp 32 gl6 1
sh create-local-job.sh dpp 32 gl6 2
sh create-local-job.sh dpp 32 gl6 3
sh create-local-job.sh dpp 32 gl6 4
sh create-local-job.sh dpp 32 gl6 5
sh create-local-job.sh dpp 32 gl6 6
sh create-local-job.sh dpp 32 gl6 7
sh create-local-job.sh dpp 32 gl6 8
sh create-local-job.sh dpp 32 gl6 9
sh create-local-job.sh dpp 32 gl6 10
sh create-local-job.sh daa 16 gl6 1
sh create-local-job.sh daa 16 gl6 2
sh create-local-job.sh daa 16 gl6 3
sh create-local-job.sh daa 16 gl6 4
sh create-local-job.sh daa 16 gl6 5
sh create-local-job.sh daa 16 gl6 6
sh create-local-job.sh daa 16 gl6 7
sh create-local-job.sh daa 16 gl6 8
sh create-local-job.sh daa 16 gl6 9
sh create-local-job.sh daa 16 gl6 10
sh create-local-job.sh daa 32 gl6 1
sh create-local-job.sh daa 32 gl6 2
sh create-local-job.sh daa 32 gl6 3
sh create-local-job.sh daa 32 gl6 4
sh create-local-job.sh daa 32 gl6 5
sh create-local-job.sh daa 32 gl6 6
sh create-local-job.sh daa 32 gl6 7
sh create-local-job.sh daa 32 gl6 8
sh create-local-job.sh daa 32 gl6 9
sh create-local-job.sh daa 32 gl6 10
sh create-local-job.sh dpp 8 gl2 1 warmup
sh create-local-job.sh dpp 8 gl6 1 warmup